@startuml NFD_CreateTeam

Player -> App : Choose new game
Player <- App : Return screen with options
Player -> App : User choose a team or solo mode and begin match

alt solo mode
    App -> Game : Request game begin
    App <- Game : Send a question
    Player <- App : Return interface with game screen

else challenge 1x1
    App -> Player : Returns screen to play with random opponent
    App -> Game : Request game begin
    App <- Game : Send a question
    Player <- App : Return interface with game screen
    
else challenge 2x2
    App -> Player : Returns Team Create Screen
    Player -> App: Search by user name
    App -> Game : Send a user name request
    Game -> App : Returns corresponding options
    App -> Player : Show the screen
    Player -> App: Select the user and click Invite
    App -> Game : Request game begin
    App <- Game : Send a question
    Player <- App : Return interface with game screen
    
else challenge 3x3
    App -> Player : Returns Team Create Screen
    Player -> App: Search by user name
    App -> Game : Send a user name request
    Game -> App : Returns corresponding options
    App -> Player : Show the screen
    Player -> App: Select the user and click Invite
    Player -> App: Search by user name
    App -> Game : Send a user name request
    Game -> App : Returns corresponding options
    App -> Player : Show the screen
    Player -> App: Select the user and click Invite
    App -> Game : Request game begin
    App <- Game : Send a question
    Player <- App : Return interface with game screen
end

@enduml
