@startuml NFD_Chat

Player -> App : Click on the chat icon
Player <- App : Open match chat
Player -> App : Write message and request sending
App -> Talk : Send message
App <-- Talk : Reply to submission
Player <- App : Show sent message

@enduml