@startuml NFD_Game

Player -> App : Choose new game
Player <- App : Return screen with options
Player -> App : User choose a team or solo mode and begin match
App -> Game : 
App <- Game : 
Player <- App : 

@enduml