@startuml
    title Command Buy Card

    actor user_team as user
    participant Card as card
    participant Command as command

    user-->card: MethodEvent event
    card->card: Command buyCard(String command)
    card->command: void execute(Card card)
    command-->>user: Card card
@enduml