@startuml

title Start Game: use case normal flow

User_team --> Game: Create game
User_team --> Game: Buy card
Game --> User_team: Return card
Game --> User_team: Sort question
User_team --> Game: Answer the question
User_team --> Game: Buy card
Game --> User_team: Return card
Game --> User_team: Count random number of game squares
@enduml