@startuml

left to right direction
skinparam packageStyle rectangle
actor user_student as student
actor user_teacher as teacher
rectangle game {
    student -- (answer)
    (question) - (game)
    (feedback) - (answer)
    (answer) - (question)
    (feedback) -- teacher

    
}



@enduml
